### PR TITLE
Update x/sys and etcd/bbolt modules to support Risc-V

### PR DESCRIPTION
**Pull request by carlosedp**
Signed-off-by: CarlosEDP <me@carlosedp.com>

Updating projects using libraries that were recently updated to support Risc-V architecture. This is required to build OpenFaaS on the new architecture.

Go upstream work is tracked on: golang/go#27532

Risc-V software support tracker on carlosedp/riscv-bringup

### CODE REVIEW

**Comment by carlosedp** [comment]
I found out a problem on this, after running `GO111MODULE=on go mod tidy && GO111MODULE=on go mod vendor`, the go.mod gets the module `github.com/nats-io/go-nats v0.0.0-00010101000000-000000000000 // indirect` but this gives me an error on building:

```
➜ go build .
go: github.com/nats-io/nats.go@v1.8.1 used for two different module paths (github.com/nats-io/go-nats and github.com/nats-io/nats.go)
```

**Comment by kozlovic** [comment]
We don't want to add dependencies for tests at this time. I skip the tidy part. Also, not sure why this added the dependency on gnatsd/go-nats. We have updated code base to avoid that...
At any rate, I don't think we want to force Go 1.13 as a dependency at this point.

**Comment by carlosedp** [comment]
Thanks, I'll just update the modules and avoid tidy to push the PR. Sorry about the 1.13 line, my bad.

**Comment by carlosedp** [comment]
Passed, thanks for the heads-up on "tidy" @kozlovic. It was really messing things up.

**Comment by kozlovic** [comment]
Thanks!

**Pull request merged**
