### PR TITLE
Little typo on readme file and add a note on FT mode

### PR DESCRIPTION
**Pull request by ivanrodolfo**
Changes from abve to above

### CODE REVIEW

**Comment by kozlovic** [comment]
@ivanrodolfo Thank! When you submit a PR about a README or something that does not require tests from running you can include `[ci skip]` in the title or content of the PR and that will skip the tests (but it's fine if you omit and tests run ;-) ).

**Comment by kozlovic** [comment]
Do you think you may have more fixes that you will want to add to this PR or should I merge?

**Comment by ivanrodolfo** [comment]
It was my first PR here! I didn't note that will run the pipeline, by now I will not report any other change! So you can merge

**Comment by kozlovic** [comment]
I wanted to add some info in FT and Clustering sections since I got several persons now mixing the two, so definitively something is missing there!
Yes, please add and I will add more later, but it's already a start and at least will alert people that they should not, even if they don't know yet why ;-)

**Pull request merged**
