### PR TITLE
[ADDED] File slices configuration, including script for archiving

### PR DESCRIPTION
**Pull request by kozlovic**
You can now configure file slices to be of a certain size. The channel
limits may still override the size of the slices.
When a file slice is supposed to be removed, if a script has been
defined, the script is invoked with the renamed file slice. The
script can then move those files for archiving.

Related to #192

### CODE REVIEW

**Comment by kozlovic** [comment]
@sfrooster Please have a look and see if it provides the same features that you wanted with #192.

**Comment by sfrooster** [comment]
It looks pretty good! So we'd just select unlimited message count, select a time per slice and specify an archive script.

Two questions:
1) If we specify a time of 1 hour say, the the first slice will start when the first message message comes. When will the second slice start? When the first message comes in after one hour from when then first slice started?

2) If we wanted to "recover" an archived file - how would we do that?  It seems like it might be supported but I'm not sure of the exact procedure.

**Comment by kozlovic** [comment]
@sfrooster To be clear: slices are removed (or script invoked) only when the slice is empty - in that all messages in it have been "removed" due to a channel limit (count, size or age) - and this is not the only file slice. So you will still need to have at least one channel limit in order to have slices removed (or script invoked).

Regarding your questions:

1. Yes. The slice is created when the first message is stored. This is the first message's timestamp on this slice that start the counter if you will. When adding a message, a timestamp is assigned. If that timestamp minus the first timestamp on the current slice is greater than the slice's max age, then a new slice is created.

2. It would be a manual step, but you could copy/move back archived slices (and remove the `.bak` extension) into the channel's directory and restart the server. I made sure that the store does not expect file sequences to be contiguous, just for that reason. Note though, that if you maintain the same channel limits on restart, it is likely that the old slice(s) would be ignored. You may need to restart with wider limits to take the old slice(s) into account.

Now, I have to revisit the setting of the slice limits. I had put this comment in the file store options:
```
	// Regardless of channel limits, the options below allow to split a message
	// log in smaller file chunks. If all those options were to be set to 0,
	// some file slice limit will be selected automatically based on the channel
	// limits.
```
but I implemented this differently (as described in README.md). I think I'll go back to the behavior described above so that slice configuration takes precedence to channel limits. Only if no slice configuration is present should I use the default max channel limit / 4 slice limit.

**Comment by sfrooster** [comment]
@kozlovic I'm a little confused by the first part above.  What I'm trying to do is something along the lines of:

- keep a week's worth of messages "online"
- archive off messages older than a week
- (optionally) have the messages (online and archived) be stored in slices that cover 24h each

Is this sort of configuration covered here?

**Comment by kozlovic** [comment]
@sfrooster You can't remove/archive slices if they are still valid. If the server has not "removed" those messages from the log, then we would have a problem when a subscriber starts and ask for messages that are supposed to be in the system but for which the file slices have disappeared.

**Comment by sfrooster** [comment]
So we set the channel limit at 7 days, the slice limit at 24 hours - yes?

**Comment by kozlovic** [comment]
@sfrooster Yes, if the only limit you set is the channel max age and the slice limit to 24 hours, what would happen is that when all messages in the first slice have expired (which may be at the end of 8th day since the last message in first slice may be close to the 24 hours limit of first slice and its max age would still be 7 days), then that slice would be removed (or script invoked).

Note: I am updating the behavior to match the comment I excerpted in previous post.

**Comment by sfrooster** [comment]
Then that seems like it would work fine.  The only hitch is that, in order to bring back an archived slice, we'd have to restart the server with a "wider" channel limit (right?).  Alternatively, we start-up an "archive" server instance (with a different cluster id), and pull from there.  Do I have that right?

**Comment by kozlovic** [comment]
@sfrooster Yes, that would work! The idea of a "archive" server instance is nice (and there you could make sure you don't specify the archive script so to not archive archived slice ;-) ), but the problem is using a different cluster id is not that simple since your applications would need to be also restarted to connect to that archive server.

**Comment by sfrooster** [comment]
I don't expect to be pulling from the archive often so just having a solution which doesn't require restarting the "primary".  We'd probably put a piece of code in place to connect to the archive server and then republish as non-streaming messages to the primary (our subscribers subscribe to both streaming and non), or something like that.  And then, when clustering comes along, we'll see how that changes things.

**Comment by sfrooster** [comment]
I've been doing some testing with this today.  All-in-all, things are working pretty well.

I'm able to setup file slices of a certain time length, have the server maintain only a certain number of these slices "online", and archive off the "old" slices using a script I created.

I'm also able to startup a second "archive only" instance and replay events out of the archived set - with a few restrictions:

- the archive server will only load starting with slice "01"
- and will only load contiguous slices: "01","02" but not "01","04"

Is this expected?

**Comment by kozlovic** [comment]
@sfrooster Does the archive server include the PR? From the code in the PR, you see that I load any message log that is of the pattern `msgs.*.dat`. There is also code when doing lookups (in `getFileForSeq`) where I simply range through the slices because I wanted to support gaps in file sequence numbers.

So, can you verify that your archive server includes this PR?

**Comment by sfrooster** [comment]
They are two instances of the same code running with different config files, on different ports with different cluster ids and different store directories.

**Comment by kozlovic** [comment]
@sfrooster I see some issues indeed. Thanks for the test, very much appreciated!

**Comment by sfrooster** [comment]
Ah, ok, cool. Glad to help!  If you'd like, let me know when the PR's updated and I'm happy to run the test again.

**Comment by kozlovic** [comment]
Will do (and running some manual tests myself)!

**Comment by kozlovic** [comment]
There are some bookkeeping issues in `filestore.go` that are easy to fix. However, in the server, I was was supporting the possible drop of messages before lastSent: say a consumer was at sequence 100, then messages are dropped due to limit and the first avail message is now 200, when consumer asks for 101, I would jump to 200, which is the store returning the first sequence as 200. Now, I would have gaps which means requiring lookups until finding the next one. Not sure if this is reasonable or not. Need to think more about that.

**Comment by kozlovic** [comment]
If we decide to support sequence gaps, then we may need to add to the store API to get the next message based on a sequence number so that stores can efficiently return it.

**Comment by sfrooster** [comment]
Are you saying the only issue is because there is a gap in the files, or that that presents an additional issue?.  I can retest, but I believe my very first test was just trying to load the fourth of 6 files - ie 1 file with no gap.

I can't imagine (but won't preclude) wanting to load gapped sequences of files - just any one file or sequence of files not necessarily beginning with 1.

As it stands, my process for archive recovery is:
- clear server.dat and clients.dat
- "de-bak" the files I want to replay
- start an instance with the archive config
- initiate a replay of "all" messages (which I can set a predicate against client side)

So it's not the sort of thing I imagine hopscotching around, meaning handling gaps seems less important to me.

**Comment by kozlovic** [comment]
Yes, as I explained there was 2 different issues that I found:

1. The first is easy to fix and is about keeping track of first/last sequence recovered since slices can be recovered in any order. 

2. If you try to recover gapped slices (say file 2 and file 4, that would contain sequences [101,200] and [401,500] respectively, the client would receive only messages from 101 to 200 and stop there because sequence 201 was not found. 

The problem 2 is something that would require a new store API to go over the message sequence gap efficiently, but as I said, having gap in a given message log was not anticipated in the early design and may cause problems, so this is the one that would require more thinking.

Since you said that this is something that you would unlikely do, I will start by fixing the file store issues and update the PR later today.

**Comment by kozlovic** [comment]
@sfrooster Ok, I have pushed the fix for file store. I have added a test and tested manually the replay of contiguous slices (not starting at 1) and it works fine for me. Let me know if you see the same.

**Comment by sfrooster** [comment]
Let me look into this further, but no, I'm not having any success.

**Comment by kozlovic** [comment]
@sfrooster Again, note that when you first start the archive server, it will create `server.dat`, etc.. so you need to restart it once if you want to be able to recover any channel directory present.

**Comment by sfrooster** [comment]
I have tried many different combinations including tests that worked yesterday, and none of them are properly replaying even a single message.

I looked at the code I compiled and am running and it seems to reflect your most recent changes.

I'll keep poking around but as far as I can tell it's not working even as well as yesterday (the archiving part does, talking only about replay).

**Comment by kozlovic** [comment]
@sfrooster I have just re-ran the manual tests 2 times and works like a charm.
To simplify the test I have the normal server started this way:
```
nats-streaming-server -store file -dir datastore -ma "10s" -file_slice_max_msgs 10 -file_slice_archive_script ./archive.sh
```
which means that each slice will contain 10 messages. 10 seconds, after the last sent message, all messages should have expired and you should have a list of `.bak` files in the directory.

For the first time I start the "archive" instance this way:
```
nats-streaming-server -cid archive -p 5222 -store file -dir arch_datastore
```
I stop it. Create the `foo` (the channel I am sending to) directory under `arch_datastore`. I then move all `.bak` to `arch_datastore/foo`. I "de-bak" the files and remove some of the slices at the beginning and end of the list. Then restart the server. I have then my client consume all messages and can see the expected list of sequence numbers.

One thing that happened to me before was that I went into `arch_datastore/foo` directory to "de-bak", and forgot to return back `../..` before starting the server. It would then create a new `arch_datastore` under `arch_datastore/foo` and so my client would not receive anything. Make sure that this is not what is happening to you.

**Comment by sfrooster** [comment]
FWIW, replay is also now not working against the non-archive server.  But it does work against an unpatched server I'm running.

Here is the output of tree:
.
├── archive
│   ├── clients.dat
│   ├── OT.Messages.DemoMessage
│   │   ├── msgs.10.dat.bak
│   │   ├── msgs.10.idx.bak
│   │   ├── msgs.11.dat.bak
│   │   ├── msgs.11.idx.bak
│   │   ├── msgs.12.dat.bak
│   │   ├── msgs.12.idx.bak
│   │   ├── msgs.13.dat.bak
│   │   ├── msgs.13.idx.bak
│   │   ├── msgs.14.dat.bak
│   │   ├── msgs.14.idx.bak
│   │   ├── msgs.1.dat
│   │   ├── msgs.1.idx
│   │   ├── msgs.2.dat.bak
│   │   ├── msgs.2.idx.bak
│   │   ├── msgs.3.dat.bak
│   │   ├── msgs.3.idx.bak
│   │   ├── msgs.4.dat.bak
│   │   ├── msgs.4.idx.bak
│   │   ├── msgs.5.dat.bak
│   │   ├── msgs.5.idx.bak
│   │   ├── msgs.6.dat.bak
│   │   ├── msgs.6.idx.bak
│   │   ├── msgs.7.dat.bak
│   │   ├── msgs.7.idx.bak
│   │   ├── msgs.8.dat.bak
│   │   ├── msgs.8.idx.bak
│   │   ├── msgs.9.dat.bak
│   │   ├── msgs.9.idx.bak
│   │   └── subs.dat
│   └── server.dat
├── archive.sh
├── nsa.conf
├── ns.conf
├── nss
│   ├── nats-server-a.log
│   ├── nats-server-a.pid
│   ├── nats-server.log
│   ├── nats-server.pid
│   └── nss_store
│       ├── clients.dat
│       ├── OT.Messages.DemoMessage
│       │   ├── msgs.15.dat
│       │   ├── msgs.15.idx
│       │   └── subs.dat
│       ├── OT.Messages.Telemetry.Events.MessageTraced
│       │   └── subs.dat
│       └── server.dat
├── nssa.conf
└── nss.conf

nss/nss_store is where the live server stores to - it's driven by ns.conf and nss.conf
archive is where the archive server pulls from - the files are moved there by archive.sh and the archive server is driven by nsa.conf and nssa.conf

Above you can see that I'm trying to make the first set of messages available - the easiest test - but the output I get is:
[20866] 2016/11/29 21:18:47.859208 [INF] Starting nats-streaming-server[nats-dev-a] version 0.3.1
[20866] 2016/11/29 21:18:47.859846 [INF] Starting nats-server version 0.9.4
[20866] 2016/11/29 21:18:47.860057 [INF] Starting http monitor on 0.0.0.0:8223
[20866] 2016/11/29 21:18:47.860199 [INF] Listening for client connections on 0.0.0.0:4223
[20866] 2016/11/29 21:18:47.860263 [INF] Server is ready
[20866] 2016/11/29 21:18:48.187702 [DBG] Did not detect another server instance.
[20866] 2016/11/29 21:18:48.188114 [DBG] STAN: Discover subject:    _STAN.discover.nats-dev-a
[20866] 2016/11/29 21:18:48.188198 [DBG] STAN: Publish subject:     _STAN.pub.4zwgDIbV3c2pBFzpKG7MDk.>
[20866] 2016/11/29 21:18:48.188268 [DBG] STAN: Subscribe subject:   _STAN.sub.4zwgDIbV3c2pBFzpKG7MFi
[20866] 2016/11/29 21:18:48.188336 [DBG] STAN: Unsubscribe subject: _STAN.unsub.4zwgDIbV3c2pBFzpKG7MHg
[20866] 2016/11/29 21:18:48.188400 [DBG] STAN: Close subject:       _STAN.close.4zwgDIbV3c2pBFzpKG7MJe
[20866] 2016/11/29 21:18:48.188878 [INF] STAN: Message store is FILE
[20866] 2016/11/29 21:18:48.188973 [INF] STAN: --------- Store Limits ---------
[20866] 2016/11/29 21:18:48.189051 [INF] STAN: Channels:                  100 *
[20866] 2016/11/29 21:18:48.189120 [INF] STAN: -------- channels limits -------
[20866] 2016/11/29 21:18:48.189216 [INF] STAN:   Subscriptions:          1000 *
[20866] 2016/11/29 21:18:48.189265 [INF] STAN:   Messages     :     unlimited
[20866] 2016/11/29 21:18:48.189318 [INF] STAN:   Bytes        :     unlimited
[20866] 2016/11/29 21:18:48.189364 [INF] STAN:   Age          :     unlimited *
[20866] 2016/11/29 21:18:48.189400 [INF] STAN: --------------------------------
[20866] 2016/11/29 21:19:17.001651 [DBG] STAN: [Client:test_pub-sub-2_17099] Connected (Inbox=_INBOX.WGBSEM7PUVRGBD7HD43VQD)
[20866] 2016/11/29 21:19:17.493017 [DBG] STAN: [Client:test_pub-sub-2_17099] Sending last message, subject=OT.Messages.DemoMessage.
[20866] 2016/11/29 21:19:17.493065 [DBG] STAN: [Client:test_pub-sub-2_17099] Added subscription on subject=OT.Messages.DemoMessage, inbox=_INBOX.WGBSEM7PUVRGT17VN24HOM
[20866] 2016/11/29 21:23:18.297105 [INF] STAN: Shutting down.
[20866] 2016/11/29 21:23:18.301528 [DBG] STAN: connection "_NSS-nats-dev-a-send" has been closed
[20866] 2016/11/29 21:23:18.301627 [DBG] STAN: connection "_NSS-nats-dev-a-general" has been closed
[20866] 2016/11/29 21:23:18.301721 [INF] Server Exiting..

and

2016-11-29T21:31:53.089Z - info: Node connected to EDA Broker: NodeID: test_pub-sub-2_83217 servicetype=EDA-Bus, formatversion=1, host=MBPMHAAN-1475.local, os=Darwin 16.1.0, environment=dev, @timestamp=2016-11-29T21:31:53.087Z, logname=application, type=EDA_Bus-application-1, severity=INFO, sequencenumber=1, logmessage=Node connected to EDA Broker: NodeID: test_pub-sub-2_83217
2016-11-29T21:31:53.526Z - info: Replaying events from undefined to undefined servicetype=EDA-Bus, formatversion=1, host=MBPMHAAN-1475.local, os=Darwin 16.1.0, environment=dev, @timestamp=2016-11-29T21:31:53.526Z, logname=application, type=EDA_Bus-application-1, severity=INFO, sequencenumber=2, logmessage=Replaying events from undefined to undefined
^C2016-11-29T21:32:06.307Z - info: caught SIGINT servicetype=EDA-Bus, formatversion=1, host=MBPMHAAN-1475.local, os=Darwin 16.1.0, environment=dev, @timestamp=2016-11-29T21:32:06.307Z, logname=application, type=EDA_Bus-application-1, severity=INFO, sequencenumber=3, logmessage=caught SIGINT
2016-11-29T21:32:06.307Z - info: caught exit servicetype=EDA-Bus, formatversion=1, host=MBPMHAAN-1475.local, os=Darwin 16.1.0, environment=dev, @timestamp=2016-11-29T21:32:06.307Z, logname=application, type=EDA_Bus-application-1, severity=INFO, sequencenumber=4, logmessage=caught exit

all my paths are fully qualified, and the archive server does not have archiving turned on (so it doesn't archive anything away)

**Comment by kozlovic** [comment]
From
```
[20866] 2016/11/29 21:19:17.493017 [DBG] STAN: [Client:test_pub-sub-2_17099] Sending last message, subject=OT.Messages.DemoMessage.
```
It looks like you are starting your consumer with LastReceived, not DeliverAllAvailable.
How many messages were you expecting to get? The list show 4 messages (seq 1 to 4) while being interrupted.

**Comment by sfrooster** [comment]
No, the way replay currently works is that we make a non-durable subscriber with max in flight 1 and  manual acks on, then we take the message we get and treat that as the last message to consider for this particular replay.

Then we make a second non-durable subscription which starts at the beginning of our window and replays events until it hits our window end or "last" message.

What you're seeing is that initial subscription to get the last message.  It's not finding any messages (and this exposes a bug in our code where we need to handle the "there are no messages currently" so I'll do that real quick) so the question is why isn't it finding any messages?  The sequence num 4 you're seeing in the other log is actually the log sequence number and not related to NATS/STAN.

**Comment by kozlovic** [comment]
I am at loss because I tried again and works fine. Are you using the PR from a branch? If so, please run:
```
go test -race -v -p=1 ./...
```
and see if all tests pass.

**Comment by sfrooster** [comment]
From which directory should I run that?

**Comment by kozlovic** [comment]
From top directory. Say you are in
```
go/src/github.com/nats-io/nats-streaming-server
```
and your current branch is:
```
$ git branch
* changes_to_filestore
master
```
Then execute the `go test` command.

**Comment by sfrooster** [comment]
mhaan@ci-sandbox-eda-01:/home/eda-test/edago/src/github.com/nats-io/nats-streaming-server$ git branch
* fix201
  master
mhaan@ci-sandbox-eda-01:/home/eda-test/edago/src/github.com/nats-io/nats-streaming-server$ git status
On branch fix201
nothing to commit, working directory clean
mhaan@ci-sandbox-eda-01:/home/eda-test/edago/src/github.com/nats-io/nats-streaming-server$ go test -race -v -p=1 ./...
vendor/github.com/gogo/protobuf/proto/proto3_proto/proto3.pb.go:21:8: cannot find package "github.com/gogo/protobuf/types" in any of:
	/home/eda-test/edago/src/github.com/nats-io/nats-streaming-server/vendor/github.com/gogo/protobuf/types (vendor tree)
	/usr/local/go/src/github.com/gogo/protobuf/types (from $GOROOT)
	/home/eda-test/edago/src/github.com/gogo/protobuf/types (from $GOPATH)
vendor/github.com/golang/protobuf/proto/proto3_proto/proto3.pb.go:22:8: cannot find package "github.com/golang/protobuf/proto/testdata" in any of:
	/home/eda-test/edago/src/github.com/nats-io/nats-streaming-server/vendor/github.com/golang/protobuf/proto/testdata (vendor tree)
	/usr/local/go/src/github.com/golang/protobuf/proto/testdata (from $GOROOT)
	/home/eda-test/edago/src/github.com/golang/protobuf/proto/testdata (from $GOPATH)

**Comment by kozlovic** [comment]
It's probably that your GOPATH is not set correctly based on the directory you are in.
How can you compile the PR 201 if you can't run the tests? How do you usually compile and test a PR?

**Comment by kozlovic** [comment]
The `nats-streaming-server` directory should be in `go/src/github.com/nats-io/`

**Comment by sfrooster** [comment]
/home/eda-test/edago/src/github.com/nats-io/nats-streaming-server$ echo $GOPATH
/home/eda-test/edago

**Comment by sfrooster** [comment]
My GOPATH is set correctly, as you can see.  To build and run a PR, I:
cd into src/github.com/nats-io/nats-streaming-server
- go get -u
- git fetch origin pull/201/head:fix201
- git checkout fix201
- go build
- go install

**Comment by sfrooster** [comment]
I can try and play with it more tomorrow and see if I can find-out what's going on - or, you can merge it if you think it's good and I'll rerun my tests against master.

**Comment by kozlovic** [comment]
First, the `go get -u` produce an error for me. If I try to download from a different location that my usual go directory, and then checkout the branch, do `go build` then `go install`, the executable is actually not the one from the branch I just built. I can verify that by changing in the branch the version number. Rebuild and install, I see the version is not same. If I simply build (leave the executable locally) and execute from there I see the updated version and again, everything seem to be working fine for me.

**Comment by sfrooster** [comment]
mhaan@ci-sandbox-eda-01:/home/eda-test/edago/src/github.com/nats-io/nats-streaming-server$ go get -u
# cd /home/eda-test/edago/src/github.com/nats-io/nats-streaming-server; git pull --ff-only
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> fix201

package github.com/nats-io/nats-streaming-server: exit status 1
mhaan@ci-sandbox-eda-01:/home/eda-test/edago/src/github.com/nats-io/nats-streaming-server$ git checkout master
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
mhaan@ci-sandbox-eda-01:/home/eda-test/edago/src/github.com/nats-io/nats-streaming-server$ go get -u
mhaan@ci-sandbox-eda-01:/home/eda-test/edago/src/github.com/nats-io/nats-streaming-server$

I was on my PR branch, so go get -u failed, then I checkout master, and go get -u succeeds - I don't know why it's failing for you.

I compared sizes and create times before and after via "ls -l `which nats-streaming-server`" and they changed.

I'm building in src/github.com/nats-io/nats-streaming-server which is also the repo directory.

Clearly my process works or I wouldn't have gotten the results I did yesterday - archiving working, retrieval almost working.  I've also verified the changes from your PR are in the code I'm building from.

I don't see any issues with my process but, if you do, please share.

**Comment by kozlovic** [comment]
Ok, then can you try to consume with a go client from the `go-nats-streaming` repo?
```
go run examples/stan-sub.go -s nats://<host>:4223 -c nats-dev-a -id me -all OT.Messages.DemoMessage
```
to see if this is a problem with the consumer? Again, everything works fine for me, so I am at loss.

I am not sure if merging is a good idea if you get such failure. But again, all my tests (`go test`) and manual tests work for me...

**Comment by sfrooster** [comment]
Per our discussions, I've re-run my set of tests using your new PR, and modifying my testing to *not* remove server.dat between runs.  All the issues seem to be resolved and everything is working as expected.  Looks good!!

**Pull request merged**
